HOLIDAY_MODE: str = 'HOLIDAY'
QM_HOTWATER_BOOST: str = 'QM_HOTWATER_BOOST'
QM_VENTILATION_BOOST: str = 'QM_VENTILATION_BOOST'
QM_ONE_DAY_AWAY: str = 'QM_ONE_DAY_AWAY'
QM_SYSTEM_OFF: str = 'QM_SYSTEM_OFF'
QM_ONE_DAY_AT_HOME: str = 'QM_ONE_DAY_AT_HOME'
QM_PARTY: str = 'QM_PARTY'

MODE_AUTO: str = 'AUTO'
MODE_ON: str = 'ON'
MODE_OFF: str = 'OFF'
MODE_MANUAL: str = 'MANUAL'
MODE_DAY: str = 'DAY'
MODE_NIGHT: str = 'NIGHT'
QUICK_VETO: str = 'QUICK_VETO'

THERMOSTAT_MAX_TEMP: float = 30
FROST_PROTECTION_TEMP: float = 5
