HOLIDAY_MODE = 'HOLIDAY'
QM_HOTWATER_BOOST = 'QM_HOTWATER_BOOST'
QM_VENTILATION_BOOST = 'QM_VENTILATION_BOOST'
QM_ONE_DAY_AWAY = 'QM_ONE_DAY_AWAY'
QM_SYSTEM_OFF = 'QM_SYSTEM_OFF'
QM_ONE_DAY_AT_HOME = 'QM_ONE_DAY_AT_HOME'
QM_PARTY = 'QM_PARTY'

MODE_AUTO = 'AUTO'
MODE_ON = 'ON'
MODE_OFF = 'OFF'
MODE_MANUAL = 'MANUAL'
MODE_DAY = 'DAY'
MODE_NIGHT = 'NIGHT'
QUICK_VETO = 'QUICK_VETO'

THERMOSTAT_MAX_TEMP = 30
FROST_PROTECTION_TEMP = 5
